const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Behaviors.custom,
		C3.Behaviors.Bullet,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsSuspended,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetJumpSustain,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Browser.Acts.GoToURL
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Health: 0},
	{jumpcount: 0},
	{Invincible: 0},
	{frozen: 0},
	{BoundToLayout: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{Custom: 0},
	{Bullet: 0},
	{player: 0},
	{Solid: 0},
	{ground: 0},
	{border: 0},
	{boss: 0},
	{fireball: 0},
	{boom: 0},
	{heart1: 0},
	{healthBar: 0},
	{heart2: 0},
	{heart3: 0},
	{heart4: 0},
	{heart5: 0},
	{heart6: 0},
	{title: 0},
	{Mouse: 0},
	{background: 0},
	{startButton: 0},
	{storyButton: 0},
	{controlButton: 0},
	{creditButton: 0},
	{startText: 0},
	{storyText: 0},
	{controlText: 0},
	{creditText: 0},
	{stillBackground: 0},
	{controlBox: 0},
	{rightArrow: 0},
	{controlFireText: 0},
	{leftArrow: 0},
	{upArrow: 0},
	{controlAirFireText: 0},
	{downArrow: 0},
	{tipText: 0},
	{nextPage: 0},
	{nextPageText: 0},
	{homeButton: 0},
	{homeText: 0},
	{rightArrowText: 0},
	{leftArrowText: 0},
	{upArrowText: 0},
	{downArrowText: 0},
	{backPage: 0},
	{backPageText: 0},
	{jumpKey: 0},
	{rightKey: 0},
	{leftKey: 0},
	{movementText: 0},
	{rememberText: 0},
	{leftText: 0},
	{rightText: 0},
	{jumpText: 0},
	{creatorText: 0},
	{artText: 0},
	{storyCreditText: 0},
	{musicText: 0},
	{storyCutscene: 0},
	{nextScreenButton: 0},
	{endCutscene: 0},
	{nextScreenButtonFinal: 0},
	{winScreen: 0},
	{loseScreen: 0},
	{restartText: 0},
	{gameBG: 0},
	{torch1: 0},
	{torch2: 0},
	{torch3: 0},
	{bossSpawn: 0},
	{invincibleText: 0},
	{bulletNumber: 0},
	{ghostBulletRed: 0},
	{redWall: 0},
	{health: 0},
	{blueWall: 0},
	{Browser: 0},
	{musicButton: 0},
	{linkText: 0},
	{Audio: 0},
	{homeButtonMenu: 0},
	{damageLine: 0},
	{damageLineMirrored: 0},
	{damageExplode: 0},
	{explosionAttack: 0},
	{chargeBorder: 0},
	{damageLightning: 0},
	{lightningStrike: 0},
	{BossAttack: 0},
	{HP: 0},
	{gameStart: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	border: class extends self.ISpriteInstance {},
	boss: class extends self.ISpriteInstance {},
	fireball: class extends self.ISpriteInstance {},
	boom: class extends self.ISpriteInstance {},
	heart1: class extends self.ISpriteInstance {},
	healthBar: class extends self.ISpriteInstance {},
	heart2: class extends self.ISpriteInstance {},
	heart3: class extends self.ISpriteInstance {},
	heart4: class extends self.ISpriteInstance {},
	heart5: class extends self.ISpriteInstance {},
	heart6: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	background: class extends self.ISpriteInstance {},
	startButton: class extends self.ISpriteInstance {},
	storyButton: class extends self.ISpriteInstance {},
	controlButton: class extends self.ISpriteInstance {},
	creditButton: class extends self.ISpriteInstance {},
	startText: class extends self.ITextInstance {},
	storyText: class extends self.ITextInstance {},
	controlText: class extends self.ITextInstance {},
	creditText: class extends self.ITextInstance {},
	stillBackground: class extends self.ISpriteInstance {},
	controlBox: class extends self.ISpriteInstance {},
	rightArrow: class extends self.ISpriteInstance {},
	controlFireText: class extends self.ITextInstance {},
	leftArrow: class extends self.ISpriteInstance {},
	upArrow: class extends self.ISpriteInstance {},
	controlAirFireText: class extends self.ITextInstance {},
	downArrow: class extends self.ISpriteInstance {},
	tipText: class extends self.ITextInstance {},
	nextPage: class extends self.ISpriteInstance {},
	nextPageText: class extends self.ITextInstance {},
	homeButton: class extends self.ISpriteInstance {},
	homeText: class extends self.ITextInstance {},
	rightArrowText: class extends self.ITextInstance {},
	leftArrowText: class extends self.ITextInstance {},
	upArrowText: class extends self.ITextInstance {},
	downArrowText: class extends self.ITextInstance {},
	backPage: class extends self.ISpriteInstance {},
	backPageText: class extends self.ITextInstance {},
	jumpKey: class extends self.ISpriteInstance {},
	rightKey: class extends self.ISpriteInstance {},
	leftKey: class extends self.ISpriteInstance {},
	movementText: class extends self.ITextInstance {},
	rememberText: class extends self.ITextInstance {},
	leftText: class extends self.ITextInstance {},
	rightText: class extends self.ITextInstance {},
	jumpText: class extends self.ITextInstance {},
	creatorText: class extends self.ITextInstance {},
	artText: class extends self.ITextInstance {},
	storyCreditText: class extends self.ITextInstance {},
	musicText: class extends self.ITextInstance {},
	storyCutscene: class extends self.ISpriteInstance {},
	nextScreenButton: class extends self.ISpriteInstance {},
	endCutscene: class extends self.ISpriteInstance {},
	nextScreenButtonFinal: class extends self.ISpriteInstance {},
	winScreen: class extends self.ISpriteInstance {},
	loseScreen: class extends self.ISpriteInstance {},
	restartText: class extends self.ITextInstance {},
	gameBG: class extends self.ISpriteInstance {},
	torch1: class extends self.ISpriteInstance {},
	torch2: class extends self.ISpriteInstance {},
	torch3: class extends self.ISpriteInstance {},
	bossSpawn: class extends self.ISpriteInstance {},
	invincibleText: class extends self.ITextInstance {},
	ghostBulletRed: class extends self.ISpriteInstance {},
	redWall: class extends self.ISpriteInstance {},
	blueWall: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	musicButton: class extends self.ISpriteInstance {},
	linkText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	homeButtonMenu: class extends self.ISpriteInstance {},
	damageLine: class extends self.ISpriteInstance {},
	damageLineMirrored: class extends self.ISpriteInstance {},
	damageExplode: class extends self.ISpriteInstance {},
	explosionAttack: class extends self.ISpriteInstance {},
	chargeBorder: class extends self.ISpriteInstance {},
	damageLightning: class extends self.ISpriteInstance {},
	lightningStrike: class extends self.ISpriteInstance {}
}